---
- name: Update apt-get cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - ufw
    - build-essential
    - curl
    - libpcre3-dev
    - python-apt
    - python-pip
    - python-pycurl
    - php5
    - php5-mysql
    - libcurl3-dev
    - php5-curl
    - php5-gd
    - php5-json
    - php5-xmlrpc
    - php5-xsl
    - php5-mcrypt

- name: Install boto
  pip: name=boto state=latest
- name: Configure boto
  template: >
    src=boto.config
    dest="~/.boto"
- name: Add host to route53
  ignore_errors: yes
  # async: yes
  route53: >
    command=create
    zone={{ fqdn_zone }}
    record="{{ ec2_tag_Name }}{{ domain }}"
    type=A
    ttl=7200
    value="{{ ec2_private_ip_address }}"
    overwrite=true
    retry_interval=10

- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow
- name: Set other UFW policy
  ufw: state=enabled direction=incoming policy=deny
